TravelingDiaries/Models/Hotel.cs
namespace TravelingDiaries.Models
{
    public class Hotel
    {
        public int HotelId { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string ImageUrl { get; set; }
        public int DestinationId { get; set; }
        public string ShortDescription { get; set; }

        public string Description { get; set; }

        public bool IsRoomEmpty { get; set; }


    }
}

TravelingDiaries/Models/HotelMini.cs
using System.ComponentModel.DataAnnotations;

namespace TravelingDiaries.Models
{
    public class HotelMini
    {
        [Key]
        public int HotelId { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string ImageUrl { get; set; }
        
    }
}

TravelingDiaries/Controllers/HotelController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using TravelingDiaries.Models;

namespace TravelingDiaries.Controllers
{
    public class HotelController : Controller
    {
        private readonly IMapper mapper;
        public HotelController(IMapper mapper)
        {
            this.mapper = mapper;
        }
        /*
                to retrive all the Hotels*/

        public async Task<IActionResult> HotelMini()
        {
            IEnumerable<HotelMini> hotels = new List<HotelMini>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://localhost:7015/Hotel/GetAllHotels"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    hotels = JsonConvert.DeserializeObject<IEnumerable<HotelMini>>(apiResponse);
                }

            }

            var HotelMini = mapper.Map<IEnumerable<HotelMini>>(hotels);
            return View(HotelMini);
        }
        public async Task<IActionResult> GetAllHotels()
        {
            IEnumerable<Hotel> hotels = new List<Hotel>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://localhost:7015/Hotel/GetAllHotels"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    hotels = JsonConvert.DeserializeObject<IEnumerable<Hotel>>(apiResponse);
                }

            }
            return View(hotels);

        }


 /*       to get the details of single Hotel*/

        public async Task<IActionResult> HotelDetail(int? id)
        {
            var hotel = new Hotel();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://localhost:7015/Hotel/GetHotelById?id="+id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    hotel = JsonConvert.DeserializeObject<Hotel>(apiResponse);
                }

            }

            ViewData["ID"] = id;
            return View(hotel);

        }


    }
}

TravelingDiaries/Views/Hotel/GetAllHotels.cshtml
@model IEnumerable<TravelingDiaries.Models.Hotel>

@{
    ViewData["Title"] = "GetAllHotels";
}

 <style>
        body{
              /*background-image: url("https://images.pexels.com/photos/705773/pexels-photo-705773.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2");*/
              
              height: 100%;
             

                background:white;
              color:black;
        
        }
    </style>

<h1>Choose Your Luxirious Stay !!</h1>

<body>
    @foreach(var hotel in Model){

<div class="card border-danger mb-3" style="max-width: 20rem; display:inline-block;margin:20px;">
  <img class="card-img-top" src="@hotel.ImageUrl" alt="Card image cap" style="height:213px">
  <div class="card-body">
    <h5 class="card-title"><strong>@hotel.Name</strong></h5>
   <div style=" height:96px;width:288px;"><p class="card-text">@hotel.ShortDescription</p></div> 
    <h6 class="card-text"><strong> Rs:@hotel.Price</strong></h6>

    <a asp-controller="Hotel" asp-route-id="@hotel.HotelId" asp-action="HotelDetail" class="btn btn-primary">Know More</a>
  </div>
</div>



}
</body>

TravelingDiaries/Views/Hotel/HotelDetail.cshtml
@model TravelingDiaries.Models.Hotel

@{
    ViewData["Title"] = "HotelDetail";
}

<style>
        body{
             background-image: url("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYqKOT9rNEdBJ6_FeFyBEeOX0G769FERYXPZEOTKrVbw&s");
 background-color: pink;  
 color:black;
        }
    </style>

    <div>
  <h2>@Model.Name</h2>
  <div class="thumbnail">
    <img alt="@Model.Name"  width = "800px" height = "500px" src="@Model.ImageUrl">
    <hr />
    <br />
    <div class="caption-full">
        <h3 class="pull-right">Rs.@Model.Price</h3>
        
        <h4>@Model.ShortDescription</h4>
        <p>@Model.Description</p>


   <button type="button" class="btn btn-dark"><a  style="text-decoration:none; color:white"; asp-action="AddToShoppingCart" asp-controller="ShoppingCart" asp-route-id=@ViewData["ID"]>Book Now</a></button>

   <button type="button" class="btn btn-dark">   <a style="text-decoration:none; color:white;"  asp-action="Index" asp-controller="Home">Back to List</a></button>
</div>

  

TravelingDiaries/Views/Hotel/HotelMini.cshtml
@model IEnumerable<TravelingDiaries.Models.HotelMini>

@{
    ViewData["Title"] = "HotelMini";
}

<style>
    body{
        background:cadetblue;
        color:black;
    }
</style>


<h1>HotelMini</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImageUrl)
            </th>
       
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                <img src = @item.ImageUrl style="width:200px;height:200px">
            </td>

        </tr>
}
    </tbody>
</table>